version: '3'
services:
  dl:
    build:
      context: .
      dockerfile: "Dockerfile"
    command: bash
    volumes:
      - .:/app
      - python-packages:/root/.local/share
    ports:
      - "8888:8888"
      - "11111:11111"
    image: tyoyo/dl
    tty: true
volumes:
  python-packages:
