name: Build and Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker Build
      run: docker-compose build

    - name: Setup for publishing coverage
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        docker-compose run --rm dl ./cc-test-reporter before-build

    - name: Pytest
      run: docker-compose run --rm dl pytest --cov-report xml

    - name: Publish code coverage
      run: docker-compose run --rm dl ./cc-test-reporter after-build -t coverage.py -r ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}

    - name: Python code style test (flake8)
      run: docker-compose run --rm dl flake8 --show-source

    - name: Publish Docker image to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: tyoyo/dl
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
