name: Build and Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker Build
      run: docker-compose build

    - name: Docker Up
      run: docker-compose up -d

    # - name: Pytest
    #   run: docker-compose run --rm dl pytest

    - name: Pytest
      run: docker-compose exec dl pipenv run pytest

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: 4f72a5a47c399fd273c27accb86644eda941ab011122ce872205971c5d8ed378
      with:
        coverageCommand: docker-compose exec dl pipenv run coverage report -m
        debug: true

    - name: Python code style test (flake8)
      run: docker-compose run --rm dl flake8 --show-source

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tyoyo/dl
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
