name: Build and Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker Build
      run: docker-compose build

    # - name: Pytest
    #   run: docker-compose run --rm dl pytest

    - name: Pytest & publish code coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
      with:
        coverageCommand: docker-compose run --rm dl pytest --cov-report xml
        debug: true

    - name: Python code style test (flake8)
      run: docker-compose run --rm dl flake8 --show-source

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tyoyo/dl
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
