name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker Build
      run: docker-compose build

    - name: Pytest
      run: docker-compose run --rm dl pytest

    - name: Python code style test (flake8)
      run: docker-compose run --rm dl flake8 --show-source

    - name: Push to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      run: docker-compose push
